FROM scratch

ARG TARGETARCH
ARG WOW_SOURCE_REVISION
ARG WOW_BUILD_VERSION

LABEL org.opencontainers.image.title="WOW Sidecar" \
      org.opencontainers.image.revision="$WOW_SOURCE_REVISION" \
      org.opencontainers.image.version="$WOW_BUILD_VERSION"

COPY build/go-container/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY build/go-container/${TARGETARCH}/wow-sidecar /wow-sidecar

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

USER 10001:10001
EXPOSE 8080

ENTRYPOINT ["/wow-sidecar"]
